[tool.poetry]
name = "style-mate"
version = "0.1.0"
description = ""
authors = ["samiya"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
